# Generated by Django 5.0.7 on 2024-07-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
