# Generated by Django 5.0.7 on 2024-07-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_area_group_alter_image_image_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
